# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-20 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import pinit.screenshot.models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='Img',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=pinit.screenshot.models.get_storage_path),
        ),
    ]
